In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

In [3]:
import tensorflow.compat.v1 as tf

In [4]:
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [5]:
one = tf.constant(1)
one

<tf.Tensor 'Const:0' shape=() dtype=int32>

In [6]:
two = tf.Variable(2)
two

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

In [7]:
new_variable = tf.add(one,two)  # added constant and variable
new_variable

<tf.Tensor 'Add:0' shape=() dtype=int32>

In [8]:
# variable value can be changed:
updated = tf.assign(two,new_variable)
updated

<tf.Tensor 'Assign:0' shape=() dtype=int32_ref>

In [9]:
# Initialization Step:
# init_op = tf.initialize_all_variables()
init_op = tf.global_variables_initializer()  # Standard initializer=> initialises all codes

In [10]:
# Create A Session :
sess = tf.Session()         # sess.close() => Closes/ends the session =>check ln 38 for application

In [11]:
# initialize variables :
sess.run(init_op)

In [12]:
print(sess.run(two))

2


In [13]:
# =============== New Outlook =============

In [14]:
# 1. Create A Variable:
zero = tf.Variable(0)
zero

<tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>

In [15]:
# 2. Create A Constant :
one = tf.constant(1)
one

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [16]:
# 3. Do An operation:
new_value = tf.add(zero,one)
new_value

<tf.Tensor 'Add_1:0' shape=() dtype=int32>

In [17]:
# 4. Change value of a variable:
updated = tf.assign(zero,new_value)
updated

<tf.Tensor 'Assign_1:0' shape=() dtype=int32_ref>

In [18]:
# 5. Let's see what happens if we change value of constant:
# update_constant = tf.assign(one, ten)     #Error Message

In [19]:
# 6. Initialization Step:
# init_op = tf.initialize_all_variables()
init_op = tf.global_variables_initializer()  # Standard initializer=> initialises all codes   #i

In [20]:
# 7. Create A Session:
sess = tf.Session()

In [21]:
# 8a. Initialize variables:
sess.run(init_op)                                                                            #ii

In [22]:
# 8b. 
print(sess.run(zero))

0


In [23]:
# Launch the graph in a session.
with tf.compat.v1.Session() as sess:
    
# Build a graph.
    a = tf.constant(5.0)
    b = tf.constant(6.0)
    c = a * b

# Evaluate the tensor `c`.
    print(sess.run(c))

30.0


In [24]:
# ==========For loop: ===========

In [25]:
zero = tf.Variable(0)
zero

<tf.Variable 'Variable_2:0' shape=() dtype=int32_ref>

In [26]:
one = tf.constant(1)
one

<tf.Tensor 'Const_4:0' shape=() dtype=int32>

In [27]:
new_value = tf.add(zero,one)
new_value

<tf.Tensor 'Add_2:0' shape=() dtype=int32>

In [28]:
updated = tf.assign(zero,new_value)
updated

<tf.Tensor 'Assign_2:0' shape=() dtype=int32_ref>

In [29]:
sess = tf.Session()

#### Placeholder

In [30]:
import tensorflow.compat.v1 as tf

In [31]:
tf.disable_v2_behavior()

In [32]:
a = tf.placeholder(tf.float32)

In [33]:
b = a*2

Feeding a Placeholder with a Scalar:

In [34]:
sess = tf.Session()

In [35]:
result = sess.run(b, feed_dict={a:3})
#result = sess.run(b,{a:3})
print(result)

6.0


Feeding a Placeholder with a Vector

In [36]:
result = sess.run(b,feed_dict={a:[3,4,5]})
print(result)

[ 6.  8. 10.]


Feeding a placeholder with  multidimensional Vector:

In [37]:
dictionary = {a:[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24]]}
result = sess.run(b,feed_dict = dictionary)
print(result)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]
 [20. 22. 24.]
 [26. 28. 30.]
 [32. 34. 36.]
 [38. 40. 42.]
 [44. 46. 48.]]


In [38]:
sess.close()

#### Syntax For Creating Session- ('with' block) :

In [39]:
hello = tf.constant('Hello ')

In [40]:
world = tf.constant('World')

In [41]:
result = hello + world

In [42]:
# Common syntax for Session is :
with tf.Session() as sess:
    result = sess.run(hello + world)
    print(result)

b'Hello World'


In [43]:
# === Graphs ====

In [44]:
graph = tf.get_default_graph()
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Add' type=AddV2>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add_1' type=AddV2>,
 <tf.Operation 'Assign_1' type=Assign>,
 <tf.Operation 'init_1' type=NoOp>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf.Operation 'Variable_2/read' type=Identity>,
 <tf.Operat